<?php
/**
 * Created by PhpStorm.
 * User: michael
 * Date: 1/6/15
 * Time: 18:01
 */

class Chanel extends ModelBase{
    private static $instance;

    public static function getInstance()
    {
        if(self::$instance==null) {
            self::$instance=new Chanel();
        }
        return self::$instance;
    }
    public function __construct()
    {
        parent::__construct('chanel'); // TODO: Change the autogenerated stub
    }
    public function isValidName($name)
    {
        $sql="select count(*) as count from chanel where name=?";
        $result=DBConnection::read()->select($sql,array($name));

        if($result[0]->count>0) {
            return true;
        } else {
            return false;
        }
    }

    protected function createCacheObject($id, $params)
    {
        $new_object=array(
            'id'=>$id,
            'created_at'=>$this->getParamValue('created_at',$params,time()),
            'updated_at'=>$this->getParamValue('updated_at',$params,time()),
            'name'=>$this->getParamValue('name',$params,'')
        );
        return (object)$new_object;
    }

    public function getLists($device_id,$since,$limit) {
        $sql="select chanel.id,chanel.name,
                unix_timestamp(device_chanel.created_at) as created_at,
                unix_timestamp(device_chanel.updated_at) as updated_at
                from chanel
                inner join device_chanel on chanel.id=device_chanel.chanel_id
                where unix_timestamp(device_chanel.created_at) < ?
                and device_chanel.device_id=?
                order by device_chanel.created_at desc
                limit 0, ?";
        $result=DBConnection::read()->select($sql,array($since,$device_id,$limit));
    }


} 