<?php
/**
 * Created by PhpStorm.
 * User: michael
 * Date: 1/7/15
 * Time: 16:54
 */

class Device_Movie extends DBAccess{
    private static $instance;

    public static function getInstance()
    {
        if(self::$instance==null) {
            self::$instance=new Device_Movie();
        }
        return self::$instance;
    }

    public function __construct()
    {
        parent::__construct('device_movie_action'); // TODO: Change the autogenerated stub
    }

    public function registerEvent($device_id,$movie_id,$action) {
        if($action!=Constants::ACTION_LIKE && $action != Constants::ACTION_VIEW) {
            return;
        }
        // check exist event or not ==> if existed before ==> reject, if not exist ==> register new
        if(!$this->isExist($device_id,$movie_id,$action)) {
            // register new
            $this->insert(
                array(
                    'created_at'=>array('now()'),
                    'updated_at'=>array('now()'),
                    'device_id' =>$device_id,
                    'movie_id'  =>$movie_id,
                    'event'     =>$action
                )
            );
        }
    }
    public function isExist($device_id,$movie_id,$action) {
        $sql="select count(*) as cnt from device_movie_action where device_id=? and movie_id=? and event=?";
        $result=DBConnection::read()->select($sql,array($device_id,$movie_id,$action));
        if($result[0]->cnt==0) {
            return false;
        } else {
            return true;
        }
    }
} 