<?php
/**
 * Created by PhpStorm.
 * User: michael
 * Date: 1/7/15
 * Time: 17:16
 */

class Device_Chanel extends DBAccess {
    private static $instance;

    public static function getInstance()
    {
        if(self::$instance==null) {
            self::$instance=new Device_Chanel();
        }
        return self::$instance;
    }

    public function __construct()
    {
        parent::__construct('device_chanel'); // TODO: Change the autogenerated stub
    }

    public function follow($device_id,$chanel_id) {
        if(!$this->isFollowed($device_id,$chanel_id)) {
            // register follow
            $this->insert(
                array(
                    'created_at'=>array('now()'),
                    'updated_at'=>array('now()'),
                    'device_id'=>$device_id,
                    'chanel_id'=>$chanel_id
                ));
        }
    }
    public function unFollow($device_id,$chanel_id) {
        // delete record on DB
        $this->delete(array(
            'device_id'=>$device_id,
            'chanel_id'=>$chanel_id
        ));
    }
    public function isFollowed($device_id,$chanel_id) {
        $sql="select count(*) as cnt from device_chanel where device_id=? and chanel_id=?";
        $result=DBConnection::read()->select($sql,array($device_id,$chanel_id));
        if($result[0]->cnt>0) {
            return true;
        } else {
            return false;
        }
    }
} 